46 cap deployment
pulibrary/static-tables pull request #72
Opened 2024-05-13 20:02 UTC by rladdusaw

Resolves #46

2024-05-13 20:11 UTC, maxkadel commented on README.md
> +3. Visit: [localhost:3456](http://localhost:5173/)
```suggestion
3. Visit: [localhost:5173](http://localhost:5173/)
```

2024-05-13 20:14 UTC, maxkadel commented on app/services/DataService.js
> +import Papa from 'papaparse';
Do we still want this line?

2024-05-14 18:38 UTC, maxkadel commented on README.md
> +## Building for deployment
So this is part of the capistrano deployment, so how can we make that clear? I think it's nice to have here, but I initially thought we needed to do them separately for deployment

2024-05-14 18:41 UTC, maxkadel requested changes
We lost the table description somewhere in the merges

2024-05-14 18:50 UTC, rladdusaw commented
> We lost the table description somewhere in the merges

I'm seeing the [data attribute](https://github.com/pulibrary/static-tables/pull/72/files#diff-927334fc49930ff6860b35d0bc3943fc84d050b4f6b3b3b8e1d15a1e9c90f740L22) and it being used [in the template](https://github.com/pulibrary/static-tables/blob/ffd22b8185083ca33b4953cd8bc11941facdf86e/app/components/PaginatedTable.js#L174).

2024-05-14 19:12 UTC, maxkadel commented
> > We lost the table description somewhere in the merges
> 
> I'm seeing the [data attribute](https://github.com/pulibrary/static-tables/pull/72/files#diff-927334fc49930ff6860b35d0bc3943fc84d050b4f6b3b3b8e1d15a1e9c90f740L22) and it being used [in the template](https://github.com/pulibrary/static-tables/blob/ffd22b8185083ca33b4953cd8bc11941facdf86e/app/components/PaginatedTable.js#L174).

But it's not displayed on the site when it's deployed:
Staging:
![Staging site without table descirpiton](https://github.com/pulibrary/static-tables/assets/45948126/73e9c4b0-0810-463a-880a-998641756046)

Production:
![image](https://github.com/pulibrary/static-tables/assets/45948126/55a92a7b-e462-47d7-9c2e-d9e6427ed1f0)

2024-05-14 19:22 UTC, merged